// <auto-generated />
namespace Module06TP02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m2m_samourai_artmartial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m2m_samourai_artmartial));
        
        string IMigrationMetadata.Id
        {
            get { return "202004221448040_m2m_samourai_artmartial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
